name: swisscycling-vertical-backend
services:
  swisscycling-vertical-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swisscycling-vertical-backend
    ports:
        - 9010:80
    volumes:
        - swisscycling-vertical-backend-data:/code/data
    image: swisscycling-vertical-backend-image
volumes:
  swisscycling-vertical-backend-data:
    external: true
    name: swisscycling-vertical-backend-data